# Generated by Django 3.2.1 on 2021-06-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_auto_20210603_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='names',
            new_name='name',
        ),
    ]
